openapi: 3.0.1
info:
  title: api-sirius-core
  description: api-sirius-core
  contact:
    name: sirius
    email: sirius@msirius.com
  version: v1
servers:
  - url: /
paths:
  /onboarding:
    post:
      description: Onboarding new users
      operationId: siriusOnboarding
      tags:
        - Onboarding
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/payloadReqInfo'
              examples:
                onboardingResInfo:
                  value:
                    payload: Onboarding payload
      security: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payloadReqInfo'
            examples:
              onboardingReqInfo:
                value:
                  payload: Onboarding payload
  /login:
    post:
      description: Onboarding new users
      operationId: siriusLogin
      tags:
        - Login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/payloadReqInfo'
              examples:
                loginResInfo:
                  value:
                    payload: Login payload
      security: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payloadReqInfo'
            examples:
              loginReqInfo:
                value:
                  payload: Login payload
  /dispatcher:
    post:
      description: Dispatcher
      operationId: siriusDispatcher
      tags:
        - Dispatcher
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dispatcherReqInfo'
              examples:
                dispatcherResInfo:
                  value:
                    payload:
                      payload: Payload
                    uri: Uri request
      security: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dispatcherReqInfo'
            examples:
              dispatcherReqInfo:
                value:
                  payload:
                    payload: Payload
                  uri: Uri request
components:
  schemas:
    payloadReqInfo:
      properties:
        payload:
          type: string
          description: Payload
          example: Onboarding payload
    dispatcherReqInfo:
      properties:
        payload:
          $ref: '#/components/schemas/payloadReqInfo'
        uri:
          type: string
          description: Uri
          example: Uri request
  securitySchemes: {}
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
    - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
    - authorization
    - Access-Control-Allow-Origin
    - Content-Type
    - SOAPAction
    - apikey
    - testKey
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
    - DELETE
    - PATCH
    - OPTIONS
x-wso2-production-endpoints:
  urls:
    - 'http://localhost'
  type: http
x-wso2-sandbox-endpoints:
  urls:
    - 'http://localhost'
  type: http
x-wso2-basePath: /sirius/dispatcher/v1
x-wso2-transports:
  - http
  - https
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
tags:
  - name: Dispatcher
  - name: Login
  - name: Onboarding
